---
title: Jalu Kaba X
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jalukaba.x@gmail.com
description: 'Seorang pengangguran yang suka iseng nulis di web dan blognya sendiri. '
baseurl: 
url: 
twitter_username: jalukaba_x
github_username: jalukaba-x
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
instagram_user: jalukaba_x
