---
title: JX Site
email: jalukaba.x@gmail.com
description: ''
baseurl: ''
url: https://jalukaba-x.github.io
twitter_username: jalukaba_x
github_username: jalukaba-x
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
timezone: Etc/UTC
